name: labbaika
description: labbaika mobile system.

publish_to: "none"

#top level number is used if there is a new feature (example 1.0.0)
#second level is used when add new subfeature (example 0.1.0)
#third level is used when bug is fixed (example 0.0.1)

version: 1.0.8+1

environment:
  sdk: ">=2.18.0 <3.10.6"

dependencies:
  change_app_package_name: ^1.1.0
  # cached_network_image: ^3.2.2
  cached_network_image: ^3.1.0+1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.10.0
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^6.0.0
  font_awesome_flutter: ^10.1.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^10.0.0
  google_fonts: ^3.0.1
  # google_fonts: ^2.2.0
  hexcolor: ^2.0.7
  hooks_riverpod: ^2.0.0-dev.0
  # flutter_hooks: ^0.20.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  keyboard_dismisser: ^3.0.0
  logger: ^1.1.0
  barcode_scan2: ^4.2.1
  qr_code_scanner: ^1.0.1
  basic_utils: ^5.3.0
  package_info_plus: ^4.1.0
  easy_signature_pad: ^1.0.6
  signature: ^5.2.1
  webview_flutter: ^3.0.4
  # webview_flutter: ^2.0.4
  shimmer: ^2.0.0
  # collection: ^1.15.0
  # flutterflow: ^0.1.1
  syncfusion_flutter_datepicker: ^20.3.48
  top_snackbar_flutter: ^2.1.1
  # date_range_picker: ^1.0.7
  number_pagination: ^0.0.3+2
  shared_preferences: ^2.0.15
  lottie: ^1.4.3
  salomon_bottom_bar: ^3.3.1
  persistent_bottom_nav_bar: ^5.0.2
  carousel_slider: ^4.1.1
  slide_digital_clock: ^1.0.2
  dropdown_search: ^2.0.1
  # dropdown_search: ^5.0.6
  http: ^0.13.5
  path_provider: ^2.0.11
  loading_animation_widget: ^1.2.0+3
  loading_indicator: ^3.1.0
  animations: ^2.0.7
  page_transition: ^2.0.9
  floating_action_bubble: ^1.1.4
  # flutter_datetime_picker: ^1.5.1
  smooth_page_indicator: ^1.1.0
  calendar_date_picker2: ^0.5.2
  dropdown_button2: ^2.1.0
  flutter_easyloading: ^3.0.5
  need_resume: ^1.0.7+1
  get: ^4.6.5
  flutter_smart_dialog: ^4.9.2
  flutter_slidable: ^2.0.0
  audioplayers: ^4.1.0
  input_with_keyboard_control: ^1.0.8
  # flutter_ringtone_player: ^3.2.0
  # onesignal_flutter: ^3.5.1
  firebase_core: ^2.15.0
  onesignal_flutter: ^3.2.7
  # firebase_core: ^1.10.6
  cloud_firestore: ^4.8.4
  searchable_paginated_dropdown: ^1.2.0
  custom_searchable_dropdown: ^2.1.1
  dropdown_textfield: ^1.0.8
  install_plugin: ^2.1.0
  flutter_pdfview: ^1.3.1
  # pdf: ^3.10.4
  flutter_cached_pdfview: ^0.4.2

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo-app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/icons/absensi/
    - assets/icons/benefit/
    - assets/icons/peraturan/
    - assets/icons/lainya/
    - assets/images/
    - assets/sounds/
    - assets/sounds/lki-notif-ok.wav
    - assets/sounds/lki-notif-fail.wav
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-BoldItalic.ttf
    - assets/fonts/Poppins-Italic.ttf
    - assets/fonts/Poppins-Medium.ttf

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
          style: italic
